### ISSUE TITLE
I was fixed torghost after fixed still there's errors from 54, 42, 86, 71

### ISSUE THREAD

**Issue by Abbabaje** [AzizKpln/Bruter19#19]
Dear aziz
i really like all tools which you made, i was used this tool sometime ago before you update it but now, aziz it become useless it's make me sad because i was spended lot of time on it, first time i was face the torghost issue but i was understood to i just the torghost directory missing i was get it and fixed it as well and now i am still facing this problem again i was add with my issue screenshort please fix it as soon thanks.
i am using kali linux 2020.3

Traceback (most recent call last):
  File "bruter19.py", line 71, in <module>
    insta.ig_brute(mail_address,pw)
  File "/root/Bruter19/Brute/insta.py", line 54, in ig_brute
    start_insta(username)
  File "/root/Bruter19/Brute/insta.py", line 42, in start_insta
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div[2]/div/label/input"))).send_keys(username)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/support/wait.py", line 86, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

root@kali:~/Bruter19# 

![Screenshot_2020-11-19_09_02_51](https://user-images.githubusercontent.com/52299175/99640266-f1f04780-2a48-11eb-8425-ead7d53077ca.png)

**Comment by Abbabaje** [comment]
i know at now anyone facing this issue like me

**Comment by AzizKpln** [comment]
hi, im gonna fix it after i have my exams finished. I know this problem is troubling for most of users of this tool.

**Comment by ahmedfahad50** [comment]
> i know at now anyone facing this issue like me

i am also facing this problem.

**Comment by omidsan** [comment]
i am also facing this problem. I'm so sad

**Comment by ChaCroroot** [comment]
i am also Haninge this problem please fix

**Comment by tyro00** [comment]
how to solve torghost issue? kindly help me
