### ISSUE TITLE
help me chromedriver

### ISSUE THREAD

**Issue by parjanduski1** [AzizKpln/Bruter19#9]
Traceback (most recent call last):
  File "bruter19.py", line 71, in <module>
    insta.ig_brute(mail_address,pw)
  File "/home/kali/Downloads/Bruter19/Brute/insta.py", line 54, in ig_brute
    start_insta(username)
  File "/home/kali/Downloads/Bruter19/Brute/insta.py", line 40, in start_insta
    driver = webdriver.Chrome(options=options,service=serv)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 84

**Comment by AzizKpln** [comment]
read the readme.md file
